---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foo-second
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Smendowski/argo-cd-training.git
    targetRevision: HEAD
    path: environments/staging/my-app-second
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
